import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";
import { Theme } from "@radix-ui/themes";

import SessionWrapper from "@/components/SessionWrapper";
import Footer from "@/components/Footer";

import "./globals.css";
import "@radix-ui/themes/styles.css";

const notoSansThai = Noto_Sans_Thai({
  subsets: ["thai"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body>
        <SessionWrapper>
          <Theme accentColor="iris" radius="large" appearance="dark" style={notoSansThai.style} className="flex flex-col items-center">
            <main className="h-screen p-16 flex flex-col items-center justify-center">
              {children}
            </main>
            <Footer />
          </Theme>
        </SessionWrapper>
      </body>
    </html>
  );
}