import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";

import SessionWrapper from "@/components/SessionWrapper";
import Footer from "@/components/Footer";

import "./globals.css";
import "@radix-ui/themes/styles.css";

const notoSansThai = Noto_Sans_Thai({
  subsets: ["thai"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body>
        <SessionWrapper>
          <div data-is-root-theme="true" data-accent-color="violet" data-gray-color="mauve" data-has-background="true" data-panel-background="translucent" data-radius="large" data-scaling="100%" className="radix-themes dark flex flex-col items-center" style={{ ...notoSansThai.style }}>
            {children}
            <Footer />
          </div>
        </SessionWrapper>
      </body>
    </html>
  );
}